# -*- coding: utf-8 -*-

STATE_ABBR_TO_ID = {
	'AC': '12',
	'AL': '27',
	'AM': '13',
	'AP': '16',
	'BA': '29',
	'CE': '23',
	'DF': '53',
	'ES': '32',
	'GO': '52',
	'MA': '21',
	'MG': '31',
	'MS': '50',
	'MT': '51',
	'PA': '15',
	'PB': '25',
	'PE': '26',
	'PI': '22',
	'PR': '41',
	'RJ': '33',
	'RN': '24',
	'RO': '11',
	'RR': '14',
	'RS': '43',
	'SC': '42',
	'SE': '28',
	'SP': '35',
	'TO': '17',
}

STATE_ID_TO_ABBR = { id: abbr for abbr, id in STATE_ABBR_TO_ID.items() }

CAPITALS = {
	'AC': 'Rio Branco',
	'AL': 'Maceió',
	'AM': 'Manaus',
	'AP': 'Macapá',
	'BA': 'Salvador',
	'CE': 'Fortaleza',
	'DF': 'Brasília',
	'ES': 'Vitória',
	'GO': 'Goiânia',
	'MA': 'São Luís',
	'MG': 'Belo Horizonte',
	'MS': 'Campo Grande',
	'MT': 'Cuiabá',
	'PA': 'Belém',
	'PB': 'João Pessoa',
	'PE': 'Recife',
	'PI': 'Teresina',
	'PR': 'Curitiba',
	'RJ': 'Rio de Janeiro',
	'RN': 'Natal',
	'RO': 'Porto Velho',
	'RR': 'Boa Vista',
	'RS': 'Porto Alegre',
	'SC': 'Florianópolis',
	'SE': 'Aracaju',
	'SP': 'São Paulo',
	'TO': 'Palmas',
}
